/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#include "usb_device_config.h"
#include "usb.h"
#include "usb_device.h"

#include "usb_device_class.h"
#include "usb_device_hid.h"
#include "usb_device_ch9.h"
#include "usb_device_descriptor.h"

#include "usb_device_composite.h"

/*******************************************************************************
 * Definitions
 ******************************************************************************/

typedef struct _usb_hid_generic_struct
{
    uint8_t *inBuffer;
    uint8_t *outBuffer;
    uint8_t idleRate;
} usb_hid_generic_struct_t;

/*******************************************************************************
 * Prototypes
 ******************************************************************************/

static usb_status_t USB_DeviceHidGenericAction(void);

usb_status_t USB_DeviceInterface0HidGenericCallback(class_handle_t handle, uint32_t event, void *param);

usb_status_t USB_DeviceInterface0HidGenericSetConfiguration(class_handle_t handle, uint8_t configuration_idx);

usb_status_t USB_DeviceInterface0HidGenericSetInterface(class_handle_t handle, uint8_t alternateSetting);

usb_status_t USB_DeviceInterface0HidGenericInit(usb_device_composite_struct_t *deviceComposite);


/*******************************************************************************
 * Variables
 ******************************************************************************/

USB_DMA_NONINIT_DATA_ALIGN(USB_DATA_ALIGN_SIZE) static uint8_t s_GenericInBuffer[USB_INTERFACE_0_HID_GENERIC_INPUT_REPORT_LENGTH];
USB_DMA_NONINIT_DATA_ALIGN(USB_DATA_ALIGN_SIZE) static uint8_t s_GenericOutBuffer[USB_INTERFACE_0_HID_GENERIC_OUTPUT_REPORT_LENGTH];
static usb_device_composite_struct_t *s_UsbDeviceComposite;
static usb_hid_generic_struct_t s_UsbDeviceHidGeneric;

/*******************************************************************************
 * Code
 ******************************************************************************/

/*!
* @brief Sends received data and prepares for the next IN transaction.
*
* @return usb_status_t Status of USB transaction.
*/
static usb_status_t USB_DeviceHidGenericAction(void)
{
    for (int i = 0; i < USB_INTERFACE_0_HID_GENERIC_OUTPUT_REPORT_LENGTH; i++)

    {
        s_UsbDeviceHidGeneric.inBuffer[i] = s_UsbDeviceHidGeneric.outBuffer[i];
    }

    USB_DeviceHidSend(s_UsbDeviceComposite->interface0HidGenericHandle, USB_INTERFACE_0_HID_GENERIC_SETTING_0_EP_1_INTERRUPT_IN,
        (uint8_t *)s_UsbDeviceHidGeneric.inBuffer,
        USB_INTERFACE_0_HID_GENERIC_INPUT_REPORT_LENGTH);

    return USB_DeviceHidRecv(s_UsbDeviceComposite->interface0HidGenericHandle, USB_INTERFACE_0_HID_GENERIC_SETTING_0_EP_1_INTERRUPT_OUT,
        (uint8_t *)s_UsbDeviceHidGeneric.outBuffer,
        USB_INTERFACE_0_HID_GENERIC_OUTPUT_REPORT_LENGTH);
}

/*!
* @brief Function that processes class specific events.
*
* @param handle Handle to USB device class.
* @param event Class event code.
* @param param The parameter of the class specific event.
* @retur usb_status_t Status of USB transaction.
*/
usb_status_t USB_DeviceInterface0HidGenericCallback(class_handle_t handle, uint32_t event, void *param)
{
    usb_status_t error = kStatus_USB_InvalidRequest;

    switch (event)
    {
        case kUSB_DeviceHidEventSendResponse:
            break;
        case kUSB_DeviceHidEventRecvResponse:
            if (s_UsbDeviceComposite->attach)
            {
                return USB_DeviceHidGenericAction();
            }
            break;
        case kUSB_DeviceHidEventGetReport:
        case kUSB_DeviceHidEventSetReport:
        case kUSB_DeviceHidEventRequestReportBuffer:
            break;
        case kUSB_DeviceHidEventGetIdle:
        case kUSB_DeviceHidEventGetProtocol:
        case kUSB_DeviceHidEventSetIdle:
        case kUSB_DeviceHidEventSetProtocol:
            error = kStatus_USB_Success;
            break;
        default:
            break;
    }

    return error;
}

/*!
* @brief Notifies application layer about set configuration event.
*
* @param handle Handle to USB device class.
* @param configuration_idx Id of device configuration.
* @return usb_status_t Status of USB transaction.
*/
usb_status_t USB_DeviceInterface0HidGenericSetConfiguration(class_handle_t handle, uint8_t configuration_idx)
{
   usb_status_t error = USB_DeviceHidRecv(s_UsbDeviceComposite->interface0HidGenericHandle, USB_INTERFACE_0_HID_GENERIC_SETTING_0_EP_1_INTERRUPT_OUT,
        (uint8_t *)s_UsbDeviceHidGeneric.outBuffer,
        USB_INTERFACE_0_HID_GENERIC_OUTPUT_REPORT_LENGTH);
   return error;
}

/*!
* @brief Notifies application layer about set configuration event.
*
* @param class_handle_t Handle to USB device class.
* @param alternateSetting Id of device alternative setting.
* @return usb_status_t Status of USB transaction.
*/
usb_status_t USB_DeviceInterface0HidGenericSetInterface(class_handle_t handle, uint8_t alternateSetting)
{
   usb_status_t error = USB_DeviceHidRecv(s_UsbDeviceComposite->interface0HidGenericHandle, USB_INTERFACE_0_HID_GENERIC_SETTING_0_EP_1_INTERRUPT_OUT,
        (uint8_t *)s_UsbDeviceHidGeneric.outBuffer,
        USB_INTERFACE_0_HID_GENERIC_OUTPUT_REPORT_LENGTH);
   return error;
}

/*!
* @brief Initializes device structure and buffer pointers.
*
* @param *device Pointer to structure to initialize to.
* @return usb_status_t Always return kStatus_USB_Success value.
*/
usb_status_t USB_DeviceInterface0HidGenericInit(usb_device_composite_struct_t *deviceComposite)
{
    s_UsbDeviceComposite = deviceComposite;
    s_UsbDeviceHidGeneric.inBuffer = s_GenericInBuffer;
    s_UsbDeviceHidGeneric.outBuffer = s_GenericOutBuffer;
    return kStatus_USB_Success;
}
