/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_SD_B0_00 (coord J4), IMU_SCK */
/* Routed pin properties */
#define BOARD_INITPINS_IMU_SCK_PERIPHERAL                                 LPSPI1   /*!< Peripheral name */
#define BOARD_INITPINS_IMU_SCK_SIGNAL                                        SCK   /*!< Signal name */

/* GPIO_SD_B0_03 (coord K1), IMU_MISO */
/* Routed pin properties */
#define BOARD_INITPINS_IMU_MISO_PERIPHERAL                                LPSPI1   /*!< Peripheral name */
#define BOARD_INITPINS_IMU_MISO_SIGNAL                                       SDI   /*!< Signal name */

/* GPIO_SD_B0_02 (coord J1), IMU_MOSI */
/* Routed pin properties */
#define BOARD_INITPINS_IMU_MOSI_PERIPHERAL                                LPSPI1   /*!< Peripheral name */
#define BOARD_INITPINS_IMU_MOSI_SIGNAL                                       SDO   /*!< Signal name */

/* GPIO_AD_B1_08 (coord H13), RGB_R */
/* Routed pin properties */
#define BOARD_INITPINS_RGB_R_PERIPHERAL                                     PWM4   /*!< Peripheral name */
#define BOARD_INITPINS_RGB_R_SIGNAL                                            A   /*!< Signal name */
#define BOARD_INITPINS_RGB_R_CHANNEL                                          0U   /*!< Signal channel */

/* GPIO_AD_B1_09 (coord M13), RGB_G */
/* Routed pin properties */
#define BOARD_INITPINS_RGB_G_PERIPHERAL                                     PWM4   /*!< Peripheral name */
#define BOARD_INITPINS_RGB_G_SIGNAL                                            A   /*!< Signal name */
#define BOARD_INITPINS_RGB_G_CHANNEL                                          1U   /*!< Signal channel */

/* GPIO_B1_14 (coord C14), RGB_B */
/* Routed pin properties */
#define BOARD_INITPINS_RGB_B_PERIPHERAL                                     PWM4   /*!< Peripheral name */
#define BOARD_INITPINS_RGB_B_SIGNAL                                            A   /*!< Signal name */
#define BOARD_INITPINS_RGB_B_CHANNEL                                          2U   /*!< Signal channel */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
